services:
  - type: web
    name: rag-document-assistant
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
